import type { MetadataRoute } from "next";

import { absoluteUrl } from "@/lib/site";
import { episodeSlug, getAllShows, getEpisodes } from "@/lib/episodes";

/**
 * Generated sitemap covering the home page, every show page, and every
 * per-episode page. As the catalogue grows this scales automatically because
 * it is derived from the same data API the pages use.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const shows = getAllShows();

  // Stamped once at build time. The catalogue is regenerated by the weekly
  // refresh cron, so the build/deploy time is a fair freshness signal.
  const lastModified = new Date();

  const showRoutes: MetadataRoute.Sitemap = shows.map((show) => ({
    url: absoluteUrl(`/${show.slug}`),
    lastModified,
    changeFrequency: "weekly",
    priority: 0.8,
  }));

  const episodeRoutes: MetadataRoute.Sitemap = shows.flatMap((show) =>
    getEpisodes(show.slug).map((episode) => ({
      url: absoluteUrl(`/${show.slug}/${episodeSlug(episode)}`),
      lastModified,
      changeFrequency: "monthly" as const,
      priority: 0.5,
    })),
  );

  return [
    { url: absoluteUrl("/"), lastModified, changeFrequency: "weekly", priority: 1 },
    ...showRoutes,
    ...episodeRoutes,
  ];
}
